version: '3'
services:
  server:
    container_name: server
    image: kimjiseop/capstone-design-server
    expose:
      - 8082
    ports:
      - 8082:8082
    restart: on-failure
    environment:
      TZ: "Asia/Seoul" # timezone 설정
    env_file:
      - .env
    depends_on:
      - redis
    logging:
      options:
        max-size: "200m"
        max-file: "10"
  redis:
    image: redis:latest
    container_name: redis
    restart: on-failure
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    logging:
      options:
        max-size: "100m"
        max-file: "5"
  nginx:
    container_name: nginx
    image: kimjiseop/capstone-design-nginx
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - "server"
    environment:
      TZ: "Asia/Seoul" # timezone 설정
    logging:
      options:
        max-size: "200m"
        max-file: "10"

volumes:
  redis-data: